### Users API Checking
GET http://localhost:3000/api/user/ HTTP/1.1
content-type: application/json

### 
POST http://localhost:3000/api/user/registration HTTP/1.1
content-type: application/json

{
    "username": "Daniel",
    "phone": "89122725850",
    "password": "somePadafdd22fdfd"
}
